aslo/web/__init__.py
from flask import Blueprint, g, session

web = Blueprint('web', __name__, template_folder='templates',
                static_folder='static',
                static_url_path='/web/static',
                url_prefix='/<lang_code>')


@web.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)


@web.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')
    session['lang_code'] = g.lang_code


from . import views  # noqa

aslo/web/views.py
from . import web
from flask import (render_template,
                   abort, request, redirect,
                   url_for, flash, session, send_from_directory)
from flask import current_app as app
from aslo.persistence.activity import Activity
from aslo.service import activity as activity_service
from flask_babel import gettext
import os


@web.route('/', defaults={'page': 1})
@web.route('/page/<int:page>')
def index(page=1):
    # If Ignore_lang in the parameters, show all other non-translated apps
    lang_code = session['lang_code']
    ignore_lang = request.args.get('ignore_lang', False, type=bool)
    if ignore_lang:
        activities = activity_service.get_all(page=page)
    else:
        activities = activity_service.filter_by_lang_code(lang_code, page=page)

    return render_template('index.html', activities=activities,
                           lang_code=lang_code, ignore_lang=ignore_lang)


@web.route('/<bundle_id>/<activity_version>', strict_slashes=False)
def activity_detail(bundle_id, activity_version):
    lang_code = session['lang_code']
    activity_version = float(activity_version)
    activity = Activity.get_by_bundle_id(bundle_id)
    if activity is None:
        abort(404)

    release = activity_service.find_release(activity, activity_version)
    if release is None:
        abort(404)
    else:
        return render_template('detail.html', activity=activity,
                               current_release=release, lang_code=lang_code)


@web.route('/search', methods=['GET', 'POST'])
@web.route('/search/page/<int:page>', methods=['GET', 'POST'])
def search(page=1):
    if request.method == 'POST':
        name = request.form['name']
        category_option = request.form['category-option']
        category_option_query = request.form['category-option-query']
    else:
        name = request.args.get('name')
        category_option = request.args.get('category-option')
        category_option_query = request.args.get('category-option-query')

    if not name and not category_option:
        return redirect(url_for('web.index'))

    lang_code = session['lang_code']

    if not category_option_query or 'all' in category_option_query:
        category_option_query = None
    else:
        category_option_query = category_option_query.strip().lower()

    activities = activity_service.search_by_activity_name(
        lang_code=lang_code, activity_name=name,
        page=page, category_name=category_option_query)

    if name and not category_option_query:
        flash(gettext("Search Results for {}").format(name), 'success')
    elif name and category_option_query:
        flash(gettext("Search Results for {} and {} category").format(
            name, category_option), 'success')
    else:
        flash(gettext("Search Results for {} category").format(
            category_option), 'success')
    category_options = {'placeholder': category_option,
                        'actual_query': category_option_query
                        }
    return render_template('index.html', activities=activities,
                           search_query=name,
                           category_options=category_options,
                           lang_code=lang_code)


@web.route("/downloads/<bundle_id>/<bundle_name>")
def serve_bundle(bundle_id, bundle_name):
    bundle_location = os.path.join(app.config['BUILD_BUNDLE_DIR'], bundle_id)
    file_location = os.path.join(bundle_location, bundle_name)
    if os.path.exists(file_location):
        return send_from_directory(bundle_location, bundle_name)
    else:
        flash("{} doesn't exists".format(bundle_name), 'error')
        return redirect(url_for('web.index'))


@web.route('/categories/<category_name>')
@web.route('/categories/<category_name>/<int:page>')
def categories(category_name, page=1):
    lang_code = session['lang_code']
    if not category_name:
        return redirect(url_for('web.index'))
    activities = activity_service.search_by_category(
        category_name, lang_code=lang_code, page=page)
    return render_template('index.html', activities=activities,
                           lang_code=lang_code, category_query=category_name)

aslo/web/templates/detail.html
{% extends "partials/layout.html" %}

{% block title %} 
  {% if 'en' in activity.name %} 
    {{ activity.name.en }} 
  {% elif 'en_US' in activity.name %}
    {{ activity.name.en_US }} 
  {% else %} 
    {{ _("No Name") }} 
  {% endif %} 
{% endblock %} 

{% block content %}
  <div class="row">
    <div class="col-lg-5">
      <!-- Activity Card -->
      {% with activity=activity, release=current_release %}
        {% include "elements/activity_detail_card.html" %} 
      {% endwith %}

      <!-- Developers Card -->
      {% with developers=activity.developers %} 
        {% include "elements/developer_card.html" %} 
      {% endwith %}

      <!-- Screenshot Carousel -->
      {% if current_release.screenshots and (lang_code in current_release.screenshots) %}
        {% with screenshots=current_release.screenshots[lang_code].values() %}
          {% include "elements/screenshot_carousel.html" %}
        {%endwith %}
      {% endif %}
    </div>
    <div class="col-lg-6">
      {% with activity=activity, release=current_release %}
        {% include "elements/info_card.html" %} 
      {% endwith %}
    </div>
  </div>
{% endblock %}

aslo/web/templates/elements/activity_detail_card.html
<div class="card">
  <h3 class="card-header pink lighten-1 white-text text-center" style="padding: 15px;"><i class="fa fa-superpowers"></i>{{ _('Activity') }}</h3>
  <div class="card-content text-center">
    <h3 class="card-image-headline"> {{ activity.name.get(lang_code, activity.name.get('en', activity.name.get('en_US', _('No Translation') ))) }}</h3>
    <div class="card-image img-responsive">
      <img src="data:{{ activity.icon_type }};base64,{{ activity.icon|b64encode }}" alt="Loading image..." class="center-block"/>
    </div>
    <footer class="card-footer">
      <a class="btn btn-raised btn-md btn-success" href="{{ url_for('web.serve_bundle', bundle_id=activity.bundle_id, bundle_name=current_release.bundle_name) }}"> <i class="fa fa-arrow-down"></i>{{ _('Download') }}</a>
      {% if activity.previous_releases|count != 0 %}
        <div class="btn-group">
          <a href="javascript:void(0)" class="btn btn-primary btn-md btn-raised">{{ _('More Releases') }}</a>
          <a href="#" data-target="#" class="btn btn-primary btn-md btn-raised" data-toggle="dropdown"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if release != activity.latest_release %}
              <li>
                <a href="{{ url_for('web.activity_detail', bundle_id=activity.bundle_id, activity_version=activity.latest_release.activity_version) }}">
                  {{ activity.latest_release.activity_version }} ({{ _('Latest') }})
                </a>
              </li>
            {% endif %}
            {% for release in activity.previous_releases %}
              <li>
                <a href="{{ url_for('web.activity_detail', bundle_id=activity.bundle_id, activity_version=release.activity_version) }}">
                  {{ release.activity_version }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
      <a href="{{ activity.repository}}" class="btn btn-outline-secondary btn-md waves-effect"> <i class="fa fa-github fa-2x"></i>{{ _('Repo') }}</a>
    </footer>
  </div>  
</div>

aslo/web/templates/elements/developer_card.html
<div class="card hidden-xs hidden-sm">
  <h3 class="card-header info-color lighten-1 white-text text-center" style="padding: 15px;"><i class="fa fa-users"></i>{{ _('Developers') }}</h3>
  <!-- Customized from here https://bootsnipp.com/snippets/featured/carousel-product-cart-slider -->
  <div class="card-body">
    <div class="row">
      <div id="carousel-example-generic" class="carousel col-md-12 slide hidden-xs text-center" data-ride="carousel" style="padding: 30px;">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          {% for developer_batch in developers|batch(3) %}
            <div class="item {% if loop.index == 1 %} {{" active "}} {% endif %}">
              <div class="row">
                {% for developer in developer_batch %}
                  <div class="col-sm-4">
                    <div>
                      <div class="chip">
                        <img class="img-circle img-responsive" width="48px" height="48px" src="{{ developer.avatar }}+&s=48" alt="icon" />
                        <a href="{{ developer.page }}">{{ developer.name }}</a>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      
      <div class="row">
        <div class="col-md-12">
          <!-- Controls -->
          <div class="controls text-center hidden-xs">
            <a class="left fa fa-chevron-left btn btn-sm btn-primary" href="#carousel-example-generic" data-slide="prev"></a>
            <a class="right fa fa-chevron-right btn btn-sm btn-primary" href="#carousel-example-generic" data-slide="next"></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

aslo/web/templates/elements/flash_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible text-center" role="alert" style="margin-bottom: 15px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3> {{ message }} </h3>
      </div>
    {% endfor %}
{% endif %}
{% endwith %}

aslo/web/templates/elements/front_card.html
<div class="card">
  <div class="card-height-indicator"></div>
  <div class="card-content text-center">
    <h3>{{ activity.name.get(lang_code, activity.name.get('en', activity.name.get('en_US', _('No Translation') ))) }}</h3>
    <img width="80px" height="80px" src="data:{{ activity.icon_type }};base64,{{ activity.icon|b64encode }}" alt="Loading image..." class="center-block img-fluid" />
    <footer class="card-footer">
      <a class="btn btn-raised btn-success waves-effect" href="{{ url_for('web.serve_bundle', bundle_id=activity.bundle_id, bundle_name=activity.latest_release.bundle_name) }}"> <i class="fa fa-arrow-down"></i>{{ _('Download') }}</a>
      <a class="btn btn-raised btn-primary waves-effect" href="{{ url_for('web.activity_detail', bundle_id=activity.bundle_id, activity_version=activity.latest_release.activity_version) }}"> <i class="fa fa-chevron-right" aria-hidden="true"></i>{{ _('More') }}</a>
    </footer>
  </div>
</div>

aslo/web/templates/elements/info_card.html
<div class="card">
  <h3 class="card-header warning-color-dark lighten-1 white-text text-center" style="padding: 15px;"><i class="fa fa-database"></i>{{ _('Details') }}</h3>
  <div class="card-body">
    <h4 style="padding: 20px;">
      {{ activity.summary.get(lang_code, activity.summary.get('en', activity.summary.get('en_US',_('No Translation')) )) }}
    </h4>
  </div>
        
  <div class="card-footer">
    {% if activity.categories|count != 0 %}
      <div class="row" style="margin: 5px;">
        <!-- {{ _('programming')}} {{ _('robotics')}}  {{ _('internet')}} {{ _('science')}}  {{ _('maths')}} 
          {{ _('language')}}  {{ _('geography')}}  {{ _('documents')}}  {{ _('music')}}  {{ _('media')}} 
          {{ _('art')}}  {{ _('teacher')}}  {{ _('system')}} --> 
        {% for category in activity.categories %}
          <a class="badge badge-tag grey" href="{{ url_for('web.categories', category_name=category)}}" style="padding: 10px; margin:10px;"><i class="fa fa-tag"></i>{{ _(category) }}</a>
        {% endfor %}
      </div>
    {% endif %}
    {% with release=release, license=activity.license %}
      {% include "elements/meta_info_card.html" %} 
    {% endwith %}
  </div>
</div>

aslo/web/templates/elements/meta_info_card.html
<div>    
  <ul class="list-group">
    <li class="list-group-item d-flex  align-items-center">
      <div class="card-body">
        <h4 class="card-title"><i class="fa fa-chrome fa-2x fa-spin-hover"></i>&nbsp;{{ _('Web Activity') }}</h4>
        {% if release.is_web %}
          <span class="badge success-color card-text">{{ _('Yes') }}</span> 
        {% else %}
          <span class="badge danger-color card-text">{{ _('No') }}</span>
        {% endif %}
      </div>       
    </li>
    <li class="list-group-item d-flex  align-items-center">
      <div class="card-body">
        <h4 class="card-title"><i class="fa fa-hashtag fa-2x fa-spin-hover"></i>&nbsp;{{ _('Min. Sugar Version') }}</h4>
        <span class="badge ">{{ release.min_sugar_version }}</span>
      </div>       
    </li>
    <li class="list-group-item d-flex  align-items-center">
      <div class="card-body">
        <h4 class="card-title"><i class="fa fa-university fa-2x fa-spin-hover"></i>&nbsp;{{ _('License') }}</h4>
        <span class="badge badge-info info-color ">{{ license }}</span>
      </div>
    </li>
    <li class="list-group-item d-flex  align-items-center">
      <div class="card-body">
        <h4 class="card-title"><i class="fa fa-calendar fa-2x fa-spin-hover"></i>&nbsp;{{ _('Published On') }}</h4>
        <span class="badge badge-info warning-color-dark ">{{ release.timestamp.strftime("%d %b, %Y") }}</span>
      </div>
    </li>
  </ul>              
</div>

aslo/web/templates/elements/pagination.html
<!-- Pagination -->
{% if pagination.num_pages > 1 %}
<nav class="text-center">
  <ul class="pagination pagination-lg pagination-circle pg-blue mb-0">
    {% if not pagination.has_prev %}
      <li class="page-item disabled" ><a>&laquo;</a></li>
    {% else %}
      <li class="page-item">
        {% if search_query and category_options %}
          <a class="page-link" href="
          {% if ignore_lang %} 
            {{ url_for('web.search', name=[search_query], category_option=[category_options['placeholder']], category_option_query=[category_options['actual_query']], page=pagination.prev_page, ignore_lang=true) }}
          {% else %}
            {{ url_for('web.search', name=[search_query], category_option=[category_options['placeholder']], category_option_query=[category_options['actual_query']], page=pagination.prev_page) }}
          {% endif %}">&laquo;
          </a> 
        {% elif search_query %}
          <a class="page-link" href="
            {% if ignore_lang %} 
              {{ url_for('web.search', name=[search_query], page=pagination.prev_page, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.search', name=[search_query], page=pagination.prev_page) }}
            {% endif %}">&laquo;
          </a>
        {% elif category_query %}
          <a class="page-link" href="
           {% if ignore_lang %} 
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page, ignore_lang=true) }}
           {% else %}
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page) }}
           {% endif %}">&laquo;
          </a> 
        {% else %}
          <a class="page-link" href="
            {% if ignore_lang %}
              {{ url_for('web.index', page=pagination.prev_page, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.index', page=pagination.prev_page) }}
            {% endif %}">&laquo;
          </a>
        {% endif %}
      </li>
    {% endif %}

    {% for i in range(1, pagination.num_pages + 1) %}
      <li {% if pagination.page == i %} class="page-item active" {% else %} class="page-item" {% endif %}>
        {% if search_query %}
          <a href="
            {% if ignore_lang %}
              {{ url_for('web.search', name=[search_query], page=i, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.search', name=[search_query], page=i) }}
            {% endif %}">{{ i }}
          </a>
        {% elif category_query %}
          <a class="page-link" href="
           {% if ignore_lang %} 
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page, ignore_lang=true) }}
           {% else %}
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page) }}
           {% endif %}">&laquo;
          </a> 
        {% else %}
          <a class="page-link" href="
            {% if ignore_lang %}
              {{ url_for('web.index', page=i, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.index', page=i) }}
            {% endif %}">{{ i }}
          </a>
        {% endif %}
      </li>
    {% endfor %}
    
    {% if not pagination.has_next %}
      <li class="page-item disabled" ><a class="page-link">&raquo;</a></li>
    {% else %}
      <li class="page-item">
        {% if search_query %}
          <a class="page-link" href="
            {%if ignore_lang %}
              {{ url_for('web.search', name=[search_query], page=pagination.next_page, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.search', name=[search_query], page=pagination.next_page) }}
            {% endif %}">&raquo;
          </a>
        {% elif category_query %}
          <a class="page-link" href="
           {% if ignore_lang %} 
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page, ignore_lang=true) }}
           {% else %}
             {{ url_for('web.categories', category_name=category_query, page=pagination.prev_page) }}
           {% endif %}">&laquo;
          </a> 
        {% else %}
          <a class="page-link" href="
            {% if ignore_lang %}
              {{ url_for('web.index', page=pagination.next_page, ignore_lang=true) }}
            {% else %}
              {{ url_for('web.index', page=pagination.next_page) }}
            {% endif %}">&raquo;
          </a>
        {% endif %}
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<!-- End Pagination -->

aslo/web/templates/elements/screenshot_carousel.html
<div class="card hidden-xs hidden-sm">
  <h3 class="card-header success-color white-text text-center" style="padding: 15px;"><i class="fa fa-picture-o"></i>{{ _('Screenshots') }}</h3>
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <div id="screenshot-carousel" class="carousel slide img-responsive" data-ride="carousel">
          {% if screenshots|count !=0 %}
            <!-- Indicators -->
            <ol class="carousel-indicators">
              {% for i in range(screenshots|count) %}
                <li data-target="#lightbox" data-slide-to="{{i}}" {% if i==0 %} class="active" {% endif %}></li>
              {% endfor %}
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner container">
              {% for screenshot in screenshots %}
                <!-- Only first item should be active -->
                <div class="item {%if loop.index0 == 0 %}{{" active "}}{% endif %}">
                  <a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox">
                    <img src="{{screenshot[0]}}" class="img-thumbnail"  alt="Screenshot">
                 </a>
                </div>
              {% endfor %}
            
              <!-- Left and right controls -->
              <a class="left carousel-control" href="#screenshot-carousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">{{ _("Previous") }}</span>
              </a>
              <a class="right carousel-control" href="#screenshot-carousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">{{ _('Next') }}</span>
              </a>
            </div>
          {% endif %}
        </div>
        
        <style>
          /* Modified form of https://bootsnipp.com/snippets/featured/bootstrap-lightbox */
          #lightbox .modal-content {
            display: inline-block;
            text-align: center;
          }

          a.thumbnail:hover {
            border-color: transparent;
          }

          #lightbox .close {
            opacity: 1;
            color: rgb(255, 255, 255);
            background-color: rgb(25, 25, 25);
            padding: 5px 8px;
            border-radius: 30px;
            border: 2px solid rgb(255, 255, 255);
            position: absolute;
            top: -15px;
            right: -55px;
            z-index: 1032;
          }
        </style>

        <div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true">×</button>
            <div class="modal-content">
              <div class="modal-body">
                <img src="" alt="" />
              </div>
            </div>
          </div>
        </div>

        <script>
          $(document).ready(function () {
            var $lightbox = $('#lightbox');

            $('[data-target="#lightbox"]').on('click', function (event) {
              var $img = $(this).find('img'),
                src = $img.attr('src'),
                alt = $img.attr('alt'),
                css = {
                  'maxWidth': $(window).width() - 100,
                  'maxHeight': $(window).height() - 100
                };

              $lightbox.find('.close').addClass('hidden');
              $lightbox.find('img').attr('src', src);
              $lightbox.find('img').attr('alt', alt);
              $lightbox.find('img').css(css);
            });

            $lightbox.on('shown.bs.modal', function (e) {
              var $img = $lightbox.find('img');

              $lightbox.find('.modal-dialog').css({
                'width': $img.width()
              });
              $lightbox.find('.close').removeClass('hidden');
            });
          });
        </script>
      </div>
    </div>
  </div>
</div>

aslo/web/templates/index.html
{% extends "partials/layout.html" %}

{% block title %} 
  {{ _('Software Center') }} 
{% endblock %} 

{% block content %} 
  {% if activities is none or activities.items_per_page == 0 %}
    <p> {{_('No activities build yet')}} </p>
  {% else %}
    {% include 'elements/flash_messages.html' %} 
    {% for activity_row in activities.items|batch(6) %}
      <div class="row " style="margin-bottom: 15px;">
        {% for activity in activity_row %}
          <div class="col-lg-4" style="padding: 15px;">
            {% include "elements/front_card.html" %}
          </div>
        {% endfor %}
      </div>
    {% endfor %} 
  {% endif %} 
  
  {% with pagination=activities, search_query=search_query, category_query=category_query, ignore_lang=ignore_lang %} 
    {% include "elements/pagination.html" %} 
  {% endwith %} 
{% endblock %}

aslo/web/templates/partials/nav.html
<header class="large">
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <!-- header Nav Start -->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <div id="navh" class="logo1">
              <a href="{{ url_for('web.index')}}"><img src="{{ url_for('web.static', filename='img/logo.svg') }}" ></a>
            </div>
          </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1" style="padding-bottom:0px;margin-bottom: 0px;">
            <ul class="nav navbar-nav navbar-right abc">
              <li><a href="{{ url_for('web.index') }}">{{ _('Home') }}</a></li>
              <li><a href="{{ url_for('web.index') }}">{{ _('About') }}</a></li>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ _('Join Us') }}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="https://wiki.sugarlabs.org/go/Mailing_Lists" style="color:#0099FF"> {{ _('Community Mailing Lists') }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _("Developer's Guide") }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _('Start a local lab') }}</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header"></li>
                  <li><a href="http://translate.sugarlabs.org" style="color:#0099FF">{{ _('Contribute to Translation') }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _('Contribute to Usability') }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _('Contribute to Software') }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _('Contribute to Central Organisation') }}</a></li>
                  <li><a href="#" style="color:#0099FF">{{ _('Related Projects') }}</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {{ _('Blog') }}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="http://planet.sugarlabs.org" style="color:#0099FF">{{ _("Blog Archive") }}</a></li>
                </ul>
              </li>
              <li class="navbar-form">
                <form role="search" method="POST" action="{{ url_for('web.search') }}">
                  <div class="form-group">
                    <input type="text" class="form-control" name="name" placeholder="{{ _('Search') }}">
                    <input type="hidden" value="" name="category-option">
                    <input type="hidden" value="" name="category-option-query">
                    <div class="input-group small">
                      <div class="input-group-btn">
                        <button type="button" class="btn btn-md dropdown-toggle orange" data-toggle="dropdown" aria-expanded="false" style="border-radius: 35px;">
                          <i class="fa fa-tag "></i>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" id="category-option">
                          <li value="all"><a href="#"> <i class="fa "> All</i>
                          <li value="programming"><a href="#"> {{ _("programming") }}</a></li>
                          <li value="robotics"><a href="#"> {{ _("robotics") }}</a></li>
                          <li value="internet"><a href="#"> {{ _("internet") }}</a></li>
                          <li value="science"><a href="#"> {{ _("science") }}</a></li>
                          <li value="maths"><a href="#"> {{ _("maths") }}</a></li>
                          <li value="language"><a href="#"> {{ _("language") }}</a></li>
                          <li value="geography"><a href="#"> {{ _("geography") }}</a></li>
                          <li value="documents"><a href="#"> {{ _("documents") }}</a></li>
                          <li value="music"><a href="#"> {{ _("music") }}</a></li>
                          <li value="media"><a href="#"> {{ _("media") }}</a></li>                          
                          <li value="art"><a href="#"> {{ _("art") }}</a></li> 
                          <li value="teacher"><a href="#"> {{ _("teacher") }}</a></li>
                          <li value="system"><a href="#"> {{ _("system") }}</a></li>
                        </ul>
                      </div><!-- /btn-group -->
                    </div>
                  </div>
                  <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                 </form> 
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
  </div>
</div>
</header>